### Get all Archieves
GET  http://localhost:3000/api/archieve/list

### Add archieve
POST http://localhost:3000/api/archieve/add
Content-Type: application/json

{
    "description" : "Unvalid reclamation by user",
    "id" :"6356b623e9849b08107473a0"
}


