### Add a new fournisseur
POST http://localhost:3000/api/fournisseur/add
Content-Type: application/json

{
    "slug": "Soned",
    "email":"iheb@gmail.com",
    "password" : "1234",
    "addresse" : "hamem lif",
    "phone":"56249538",
    "categorie" : "Nettoyage"
}


### List all fournisseur 
GET http://localhost:3000/api/fournisseur/list

### Update fournisseur password
PUT http://localhost:3000/api/fournisseur/update/password/62fec68af7d43a186887a637/12345

### Update reclamation don by fournisseur
PUT http://localhost:3000/api/fournisseur/update/done/614dfe099530931728154cdf
Content-Type: application/json

{
    "id" : "614dfe099530931728154cdf"
}


