### Add a new fournisseur
POST http://localhost:3000/api/fournisseur/add
Content-Type: application/json

{
    "slug": "soned",
    "email":"haifadab3@gmail.com",
    "password" : "1234",
    "addresse" : "HamemLif",
    "phone":"1234",
    "categorie" : "Eclairage"
}


### List all fournisseur 
GET http://localhost:3000/api/fournisseur/list

### Update Fournisseur
PUT http://localhost:3000/api/fournisseur/update/password/62fec68af7d43a186887a637/12345



