### Add a new reclamation
POST http://localhost:3000/api/reclamation/add
Content-Type: application/json

{
    "email": "dorsaf.ferchichi@esprit.tn",
    "description":"nettoyage manqué",
    "categorie" : "Nettoyage",
    "imageURL" : "image.png",
    "localisation":"Hamem Lif",
    "etat" : "Pending",
    "fournisseur" : "636cf361310738313c37b0a9",
    "citoyen" :"636cf32d310738313c37b0a7",
    "municipality" : "62f93509e835472fac78fb4a"
}

### Get all reclamations
GET  http://localhost:3000/api/reclamation/list

### Update reclamation by status
PUT http://localhost:3000/api/reclamation/update/614dfe099530931728154cdf
Content-Type: application/json

{
    "id" : "62fec68af7d43a186887a637"
}

### Get  reclamations in progress status
GET  http://localhost:3000/api/reclamation/list/inprogress

### Get reclamation by id
GET  http://localhost:3000/api/reclamation/getReclamationById/635293a05d9c1c37ecad2129

