### Add a new reclamation
POST http://localhost:3000/api/reclamation/add
Content-Type: application/json

{
    "description":" Il y'a un probleme de batiment dans la rue 02 istambul riadh . ",
    "imageURL" : "https://images.ladepeche.fr/api/v1/images/view/5c33f1df8fe56f79e25aa38b/large/image.jpg",
    "localisation":"Riadh",
    "categorie" :"Nettoyage",
    "etat" : "Pending",
    "citoyen" :"676887bf4e50630becfc9613",
    "municipality" : "676885d54e50630becfc95fe"
}

### get count relcmamtion
POST http://localhost:3000/api/reclamation/countByCategory
Content-Type: application/json

{
    "category": "Eclairage"

}

### Get reclamation by id citoyen
GET  http://localhost:3000/api/reclamation/getReclamationByIdCitoyen/676033c5d7377c1a6c01c86e

### Get all reclamations
GET  http://localhost:3000/api/reclamation/list

### Update reclamation info
PUT http://localhost:3000/api/reclamation/updateReclamation/677aa89a9d78ae6fd0d1fe8a
Content-Type: application/json

{
    "description": "j’ai pu constater l’état d'eclairage dans lequel se trouve la rue ",
    "imageURL" : "https://images.ladepeche.fr/api/v1/images/view/5c33f1df8fe56f79e25aa38b/large/image.jpg",
    "localisation":"rades",
    "categorie" :"Eclairage"

}

### Update reclamation by status
PUT http://localhost:3000/api/reclamation/update/6782f4e738aa412b5c94797e
Content-Type: application/json

{
    "fournisseur" : "6782c3d32bf8ed119475a0af",
    "etat": "Done",
    "noteFournisseur" : " c fait",
    "noteResponsable" : " donee"

}

### Get  reclamations in progress status
GET  http://localhost:3000/api/reclamation/list/InProgress

### Get  reclamations pending status
GET  http://localhost:3000/api/reclamation/list/pending

### Get  reclamations done  status
GET  http://localhost:3000/api/reclamation/list/done

### Get  reclamations verified status
GET  http://localhost:3000/api/reclamation/list/verified

### Get  reclamations discarded status
GET  http://localhost:3000/api/reclamation/list/discarded

### Get reclamation by id
GET  http://localhost:3000/api/reclamation/getReclamationById/677aa8019d78ae6fd0d1fe7c

### Get reclamation fournisseur
GET  http://localhost:3000/api/reclamation/listfournisseurReclamation/62fec68af7d43a186887a637

