### Add a new reclamation
POST http://localhost:3000/api/reclamation/add
Content-Type: application/json

{
    "description":"  j’ai pu constater l’état de saleté dans lequel se trouve la rue . Cette situation constitue un risque tant pour la sécurité que pour la salubrité des personnes qui empruntent cette voie. ",
    "imageURL" : "https://images.ladepeche.fr/api/v1/images/view/5c33f1df8fe56f79e25aa38b/large/image.jpg",
    "localisation":"Bir Bey",
    "categorie" :"Nettoyage",
    "etat" : "Pending",
    "citoyen" :"6356b4870c29b128b45c8e9c",
    "municipality" : "62f93509e835472fac78fb4a"
}

### Get all reclamations
GET  http://localhost:3000/api/reclamation/list

### Update reclamation by status
PUT http://localhost:3000/api/reclamation/update/614dfe099530931728154cdf
Content-Type: application/json

{
    "id" : "62fec68af7d43a186887a637"
}

### Get  reclamations in progress status
GET  http://localhost:3000/api/reclamation/list/inprogress

### Get reclamation by id
GET  http://localhost:3000/api/reclamation/getReclamationById/635293a05d9c1c37ecad2129


### Get reclamation fournisseur
GET  http://localhost:3000/api/reclamation/listfournisseurReclamation/62fec68af7d43a186887a637

