### Get all users
GET  http://localhost:3000/api/user/list


### Add a new user
POST http://localhost:3000/api/user/signUp
Content-Type: application/json

{
    "username": "haifa",
    "email":"haifa.ferchichi@esprit.tn",
    "role" : "Citoyen",
    "password":"1234"
}

### Login to the application
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"haifa2@gmail.com",
    "password":"1234"
}

### List all fournisseur 
GET http://localhost:3000/api/user/list/fournisseur
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2MmY4NDAyZjdlNDUxMjE5OWM3ZmI3YmMiLCJpYXQiOjE2NjA0MzY5MTd9.H2HrDscYRw7nmO9V5aAufxWn2bUqR6OphbtdU1cHerU


